### ISSUE TITLE
[M0-Dev] Hay que decidir el lenguaje de programación

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#16]
Buenas! Se me ha asignado este repositorio para que trabaje sobre él en el objetivo 2. Trabajaré sobre la historia de usuario #13.

Lo primero que tenemos que discutir es el lenguaje de programación a utilizar para desarrollar el proyecto, así que necesito que respondas cuando puedas a este issue para empezar a plantear el resto de issues. 
Gracias de antemano!

**Comment by luistf24** [comment]
Hola @aacosa34, el lenguaje  que me gustaría usar es go en la versión 1.19.2

**Comment by luistf24** [comment]
Buenas, ya he actualizado el fichero de las historias de usuario, el de los milestones ya lo estaba, también he eliminado el PR.

**Comment by aacosa34** [comment]
Estupendo, muchas gracias!
