### ISSUE TITLE
[M0-Dev] ¿Cómo estructuramos los ficheros del proyecto?

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#18]
Issue referente a #13 

He estado pensando en cómo estructurar los ficheros y qué tiene que contener cada fichero.

He pensado en hacer un fichero para los electrodomésticos y otro para los usuarios. De este modo puedo organizar los electrodomésticos con sus datos propios como pueden ser su consumo en kWh, su nombre del modelo, su marca, etc. así como a los usuarios con sus datos personales además de los electrodomésticos que tienen en casa como un array de electrodomésticos.

**Comment by luistf24** [comment]
Buenas, me parece bien

**Comment by aacosa34** [comment]
En principio tengo pensado en que los nombres estén escritos en inglés ya que se me hace un nombre muy largo electrodoméstico para el nombre de una estructura :laughing:, me gustaria que me dijeses si te parece bien o si prefieres que lo escriba todo en español mejor :smile:

**Comment by luistf24** [comment]
La verdad es que es una cosa que no se me había ocurrido,  pero sí, mejor ponerlo en inglés :laughing:

**Comment by aacosa34** [comment]
He estado leyendo cómo se organizan los ficheros en go y he encontrado lo siguiente: https://blog.friendsofgo.tech/posts/como_estructurar_tus_aplicaciones_go/

Si te parece uso la misma estructura.

**Comment by luistf24** [comment]
> He estado leyendo cómo se organizan los ficheros en go y he encontrado lo siguiente: https://blog.friendsofgo.tech/posts/como_estructurar_tus_aplicaciones_go/
> 
> Si te parece uso la misma estructura.

Lo veo genial:ok_hand:
