### ISSUE TITLE
[M0-Dev] Concepto de electrodoméstico

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#19]
Según la #13 identifico que tenemos una objeto valor que es electrodoméstico, ya que no debe cambiar la definición de un electrodoméstico una vez definido para que no haya ambigüedades entre dos usuarios con el mismo electrodoméstico. Para ello hace falta que se diseñe un modelo para éstos.

Hay que implementar el modelo de los datos que compondrán a los usuarios del sistema. Para ello propongo que según lo hablado en el issue #18 sobre los ficheros que contendrá el modelo, en cada uno de los ficheros de las dos entidades comentadas habrá un struct que defina qué datos son propios para cada uno de dichas entidades. En princpio tengo pensado (a falta de darle un par de vueltas) que los datos básicos para un **electrodoméstico** sea el siguiente:
```
type Appliance struct {
	Name string
	Brand string
	Model string
	Consumption int
}
```
Lo dicho, me hace falta pensarlo bien todavía por si se me escapa algo. Iré escribiendo las posibles modificaciones en este issue.

**Comment by luistf24** [comment]
Buenas, en general lo veo bien, pero yo cambiaría el atributo Name de Appliance y le pondría Type por ejemplo, siendo este un enum que contendría distintos electrodomésticos como lavadora, horno etc.

**Comment by aacosa34** [comment]
Separo este issue en dos para separar ambos modelos, que me he dado cuenta de que para discutir los diferentes aspectos de cada modelo es mejor separar issues :disappointed:

**Comment by aacosa34** [comment]
> Buenas, en general lo veo bien, pero yo cambiaría el atributo Name de Appliance y le pondría Type por ejemplo, siendo este un enum que contendría distintos electrodomésticos como lavadora, horno etc.

Esto me genera un problema, y es que si hacemos un enum estamos limitando la variedad que hay de electrodomésticos. Me explico: a lo largo del día tu usas unos determinados electrodomésticos que añadirías a tu cuenta, pero otra persona puede utilizar más variedad de electrodomésticos que tu y de distintos tipos. Entonces listarlos con un enumerado parece ser interminable o que llegará a tener un tamaño inmenso. Por ello propongo dos soluciones y tu me dices cuál te parece mejor:
- Abandonamos la idea de enumerado y elegimos la solución que decidí antes, ya que si lo piensas ahí si tu y yo tenemos el mismo electrodoméstico tendremos la misma descripción ahorrando crear variables nuevas que digan el tipo. El inconveniente de esta solución es el de tener que comprobar si el electrodoméstico ha sido registrado por otro usuario a la hora de registrar los electrodomésticos de tu hogar, lo que supone una búsqueda dentro de todos los electrodomésticos registrados. 
- Usamos el enumerado limitándolo a los electrodomésticos que se usan de una manera cotidiana. De ésta manera nos evitamos la búsqueda mencionada en la solución anterior pero perdemos versatilidad a la hora de tener diferentes electrodomésticos registrados como he dicho.

Coméntame qué te parece :smile:

**Comment by luistf24** [comment]
> > Buenas, en general lo veo bien, pero yo cambiaría el atributo Name de Appliance y le pondría Type por ejemplo, siendo este un enum que contendría distintos electrodomésticos como lavadora, horno etc.
> 
> Esto me genera un problema, y es que si hacemos un enum estamos limitando la variedad que hay de electrodomésticos. Me explico: a lo largo del día tu usas unos determinados electrodomésticos que añadirías a tu cuenta, pero otra persona puede utilizar más variedad de electrodomésticos que tu y de distintos tipos. Entonces listarlos con un enumerado parece ser interminable o que llegará a tener un tamaño inmenso. Por ello propongo dos soluciones y tu me dices cuál te parece mejor:
> 
>     * Abandonamos la idea de enumerado y elegimos la solución que decidí antes, ya que si lo piensas ahí si tu y yo tenemos el mismo electrodoméstico tendremos la misma descripción ahorrando crear variables nuevas que digan el tipo. El inconveniente de esta solución es el de tener que comprobar si el electrodoméstico ha sido registrado por otro usuario a la hora de registrar los electrodomésticos de tu hogar, lo que supone una búsqueda dentro de todos los electrodomésticos registrados.
> 
>     * Usamos el enumerado limitándolo a los electrodomésticos que se usan de una manera cotidiana. De ésta manera nos evitamos la búsqueda mencionada en la solución anterior pero perdemos versatilidad a la hora de tener diferentes electrodomésticos registrados como he dicho.
> 
> 
> Coméntame qué te parece smile

Cierto, no había caído en que hay muchos electrodomésticos y eso puede ser muy problemático, así que yo creo que nos quedamos con la primera solución que propusiste

**Comment by aacosa34** [comment]
Según lo hablado en la clase de hoy, hemos decidido que como se va a realizar una API REST para poder desarrollar lo que quieren los clientes tanto en #13 como en #12, hemos optado por adaptar la implementación del modelo de electrodomésticos para ello. Ha quedado de la siguiente manera y quedará reflejado en el siguiente commit:

```
type Appliance struct {
	Name string `json:"name"`
	Brand string `json:"brand"`
	Model string `json:"model"`
	Consumption int `json:"consumption"`
}
```

Siguiendo los recursos encontrados de **go** : https://golangdocs.com/rest-api-in-golang
