### ISSUE TITLE
[M0-Dev] Concepto de usuario

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#20]
Issue separado como respuesta a la conversación de #19 

En #13 identifico que es necesario modelar qué datos se van a manejar sobre un usuario que usa el sistema.

Por lo tanto, en el caso de los **usuarios** de momento tengo estos tres datos: 
```
type User struct {
	Id int
	Name string
	Appliances []Appliance
}
```

**Comment by aacosa34** [comment]
En principio lo he estado pensando y quedaría como he descrito aquí. Si quieres que haya una autenticación por parte del usuario podría añadirle un campo que sea la contraseña.

**Comment by aacosa34** [comment]
Al igual que en el issue #19, hemos hablado hoy en clase que se va a adaptar el struct de usuarios para que también se puedan almacenar en un API REST de cara al desarrollo de futuros milestones y de cara a desarrollar la necesidad de la historia de usuario #13. Quedará de la siguiente forma reflejado en el siguiente commit:

```
type User struct {
	Name string `json:"name"`
	Last_Name string `json:"last_name"`
	Appliances []Appliance `json:"appliances"`
}
```

**Comment by JJ** [comment]
¿En qué se usa el nombre en la lógica de negocio?

**Comment by aacosa34** [comment]
> ¿En qué se usa el nombre en la lógica de negocio?

Viendolo ahora, no le veo mucha utilidad al nombre para la lógica de negocio. Lo cambio ahora.

**Comment by JJ** [comment]
> > ¿En qué se usa el nombre en la lógica de negocio?
> 
> Viendolo ahora, no le veo mucha utilidad al nombre para la lógica de negocio. Lo cambio ahora.

No me has entendido. No se trata de cambiar esto o lo otro. Se trata de que en el issue correspondiente planteéis un problema, ya que este milestone va del modelo del problema. El problema se resolverá con una serie de estructuras de datos, pero lo importante es que planteéis el problema. Por favor, leed detenidamente la documentación sobre domain driven design, errores frecuentes en la semana 6 y 7, y el guión de este objetivo.
