### ISSUE TITLE
[M0-Dev] Concepto de tramo horario

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#21]
Tal y como aparece especificado en el milestone 0, hace falta diseñar el modelo que definirá lo que es un tramo horario. Para definirlo en principio @luistf24 y yo hemos hablado que una posible implementación de dicho diseño podría ser una muy parecida a la de las entidades de usuario (#20) y electrodomésticos (#19), quedando definido en un fichero específico el tramo horario como sigue:
```
type Time_Bracket struct {
    Date time.Time
    Appliances []Appliance
}
```
El atributo _Date_ sería del tipo _time.Time_, paquete que es necesario importar en dicho fichero para poder usarlo.

**Comment by aacosa34** [comment]
Finalmente, según lo hablado hoy en clase, sólo será necesario almacenar el día de la semana y la hora a la que irá un determinado grupo de electrodomésticos. En el siguiente commit quedará reflejado el resultado final.

**Comment by JJ** [comment]
Estos issues no plantean el problema. Plantean una solución que, a falta de problema, no se puede calificar de válida o inválida. Lo que hay que plantear es para qué sirve el tramo horario y cómo se va a usar en la lógica de negocio.

**Comment by aacosa34** [comment]
> Estos issues no plantean el problema. Plantean una solución que, a falta de problema, no se puede calificar de válida o inválida. Lo que hay que plantear es para qué sirve el tramo horario y cómo se va a usar en la lógica de negocio.

Con estos issues te refieres a los que hablan de _concepto de_, ¿no? Para arreglarlo, ¿basta con cambiar el título o creamos issues nuevos?

**Comment by JJ** [comment]
> > Estos issues no plantean el problema. Plantean una solución que, a falta de problema, no se puede calificar de válida o inválida. Lo que hay que plantear es para qué sirve el tramo horario y cómo se va a usar en la lógica de negocio.
> 
> Con estos issues te refieres a los que hablan de _concepto de_, ¿no? Para arreglarlo, ¿basta con cambiar el título o creamos issues nuevos?

Igual, creo que no me estás entendiendo. No sé si hay *arreglo* posible. Tienes que seguir la metodología que se ha comentado en el guión, evitar los errores frecuentes, y entender domain driven design. Cómo lo hagas es cosa tuya.
