### ISSUE TITLE
[M0-Dev] ¿Cómo comparten los electrodomésticos los usuarios?

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#23]
Como se especifica en #12, Mario no quiere volver a introducir los datos de un electrodoméstico si ya está en el sistema. Lo que se me ocurre para mantener todos los electrodomésticos almacenados y que sean accesibles para todos es que exista un API REST que llame a una BBDD NoSQL como puede ser MongoDB o alguna parecida en la que podamos hacer consultas sobre electrodomésticos.

Así en el caso de que se quiera introducir un electrodoméstico que ya exista, se haría una consulta antes al API y si ya existe podríamos crear un objeto de tipo Appliance con los datos ya registrados y poder añadirlo al array de objetos que tiene cada usuario sin tener que decir nada más que el modelo del electrodoméstico, por ejemplo.

**Comment by luistf24** [comment]
Sí, es la opción que yo había pensado

**Comment by aacosa34** [comment]
Referencio la solucion hablada hoy en clase que he comentado en cada uno de los issues abiertos por la implementación.

#19 #20 #21

**Comment by luistf24** [comment]
Perfecto:ok_hand:
