### ISSUE TITLE
[M0-Dev] Agrupacion en tramos horarios

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#24]
En la descripción del milestone 0 se comenta que se deben agrupar los electrodomésticos en tramos horarios, pero ocurre lo siguiente:
- No aparece mencionada ni en #13 ni en #12 relacion alguna con los tramos horarios.
- Parece más una implementación de la lógica de negocio más que modelar el problema como se indica que debe hacer el M0.

**Comment by luistf24** [comment]
Estoy de acuerdo, lo cambio en un momento
