### ISSUE TITLE
[M0-dev] Aclaración de la lógica de negocio

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#25]
Trabajando sobre #13, me gustaría saber exactamente en qué consiste la aplicación y cómo usa un usuario, en este caso Hortensia, la aplicación para poder representar bien el modelo del problema.

**Comment by luistf24** [comment]
Es lo que estuvimos hablando el otro día en clase, El usuario introduce sus electrodomésticos y luego semanalmente selecciona los que quiere poner a lo largo de la semana, una vez hecho esto la aplicación generaria un planning semanal indicando en que tramos horarios es más barato ponerlos
