### ISSUE TITLE
[M0-dev] Concepto de electrodoméstico

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#26]
Haciendo referencia a la HU #13 y como se ha hablado en #25, un usuario introduce los electrodomésticos que tiene en casa para después poder planificar su uso más optimo.

Ahora necesito saber: ¿cómo se usa un electrodoméstico en el sistema?

**Comment by luistf24** [comment]
Con una función estaría

**Comment by aacosa34** [comment]
> Con una función estaría, he estado pensando que un electrodoméstico debería llevar:
> 
> * Nombre
> * Marca
> * Modelo
> * Consumo
> 
> Que te parece?

Me parece perfecto. Me pongo a representarlo.

**Comment by JJ** [comment]
> Con una función estaría, he estado pensando que un electrodoméstico debería llevar:
> 
>     * Nombre
> 
>     * Marca
> 
>     * Modelo
> 
>     * Consumo
> 
> 
> Que te parece?

Por favor, [consultad los errores frecuentes en este objetivo](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-2)

**Comment by aacosa34** [comment]
Hemos cambiado la conversación porque es verdad que la pregunta no es la más acertada para intuir cómo se modelará el problema y además él me ha propuesto el modelo de los electrodomésticos en lugar de yo proponerlo con el commit siguiente (
db7e879). Ahora estaría mejor planteado? @JJ

**Comment by aacosa34** [comment]
Para poder usar un electrodoméstico concreto habría que saber durante cuánto tiempo se usa para poder hacer el cálculo del consumo total y así poder introducirlo en un tramo horario de una forma más logica. ¿Se contempla esto dentro de la lógica de negocio? @luistf24

**Comment by luistf24** [comment]
> Para poder usar un electrodoméstico concreto habría que saber durante cuánto tiempo se usa para poder hacer el cálculo del consumo total y así poder introducirlo en un tramo horario de una forma más logica. ¿Se contempla esto dentro de la lógica de negocio? @luistf24

Bien visto, si sería necesario : ok_hand:
