### ISSUE TITLE
[M0-dev] Concepto de usuario

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#27]
Según la HU #13 y según lo hablado en #25 se puede ver que existe la necesidad de tener registrados a los usuarios del sistema para tener control de sus electrodomésticos. 

Por lo tanto tengo que saber: ¿qué cosas puede hacer un usuario en el sistema?

**Comment by luistf24** [comment]
Para este milestone lo único sería añadir electrodomésticos

**Comment by aacosa34** [comment]
> Para este milestone lo único sería añadir electrodomésticos

En la historia de usuario #13 podemos tener dos interpretaciones (para confirmar lo que hacer jeje):
- El usuario tiene registrados de alguna forma sus electrodomésticos.
- El usuario se limita a registrar electrodomésticos para su posterior uso por cualquier usuario.
En una es necesaria la estructura de datos y en otra no hace falta representar al usuario. ¿Cuál prefieres?

**Comment by luistf24** [comment]
Para este milestone solo hace falta la primera interpretación
