### ISSUE TITLE
[M0-Dev] Hay que decidir la medidas

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#28]
Para la lógica de negocio hace falta conocer el consumo de un electrodoméstico. Ahora bien, ¿en qué unidad se mide ese consumo?

También es necesario saber en qué unidad se medirá la duración de uso de un electrodoméstico.

**Comment by JJ** [comment]
Creo que os he dicho alguna vez que no debéis preguntar a la persona que lleve el repositorio qué es lo que hay que hacer. Le cuesta el mismo trabajo contestar que programarlo él.
Por otro lado, no sigue ninguna historia de usuario, ni pregunta ni respuesta tienen ninguna relación con la lógica de negocio. En general, no contribuye a un modelo del problema que es lo que se pide en este milestone.
