### ISSUE TITLE
[M0-Dev] Para poder implementar la logica de negocio hace falta saber qué unidades usa el precio.

### ISSUE THREAD

**Issue by aacosa34** [luistf24/Trozo-de-panceta#34]
Hace falta conocer el precio al que está la luz en un determinado horario, y por tanto hace falta saber también en qué unidades se representa esa información para poder modelar correctamente el tramo horario.

_Originally posted by @aacosa34 in https://github.com/luistf24/Trozo-de-panceta/issues/33#issuecomment-1310711801_

**Comment by aacosa34** [comment]
He encontrado esta [informacion](https://www.factorenergia.com/es/blog/factura-luz/kilowatio-precio-de-la-luz/) relacionada con las unidades en las que se mide el precio de la luz.

**Comment by luistf24** [comment]
Por lo que he estado mirando la unidad del tramo suele estar eh mW/h, pero el de los electrodomésticos en W/h, luego con esto y con la página que me has pasado yo diría que lo suyo es que esté el tramo en kW/h que es lo intermedio
